# Basic settings
exp_name: 'cifar10_resnet34_gram'
seed: 42

main_run:
  # Dataset settings
  dataset: 'cifar10'  
  weight_path:
  class_weights:
  data_transform:
  target_transform: 
  dataset_ood_train: 

  # The model to use and its settings
  model: 'resnet34' 
  res_pre: False
  max_pool: False
  small_conv: True
  freeze_until: 0
  model_out_size: 
  pretrained_path: '/mnt/hdd/thesis/results/cifar10_resnet34_basic/state_dicts/cifar10_resnet34_basic_199.pth'

  # The uncertainty settings
  model_unc: 'gram'
  compress: 'gram'
  power: 10
  unc_measure: 'gram_sum'
  use_layers: [0,null]

  num_batches: 
  print_every: 50
  retain_info:

  pretrained_path_unc: 
  
  # Training parameters
  epochs: 0
  batch_size: 512

#  ['tiny_imagenet', 'tiny_imagenet_nearest', 'tiny_imagenet_bicubic', 'tiny_imagenet_odin', 'lsun', 'lsun_nearest', 'lsun_bicubic', 'lsun_odin']
inference: # ['svhn', 'tiny_imagenet', 'lsun', 'places', 'cifar100', 'textures'] 
  dataset_ood_test: ['svhn', 'tiny_imagenet', 'lsun', 'places', 'cifar100', 'textures'] 
  
  infer_id: True
  infer_train: False

evaluation: #  ['svhn', 'tiny_imagenet', 'tiny_imagenet_nearest', 'tiny_imagenet_bicubic', 'tiny_imagenet_odin', 'cifar100']
  dataset_ood_test: ['svhn', 'tiny_imagenet', 'lsun', 'places', 'cifar100', 'textures'] 
  
evaluation_training:
  pretrained_path_unc: '/mnt/hdd/thesis/results/cifar10_resnet34_maha/state_dicts/'
  dataset_ood_test: ['svhn', 'tiny_imagenet']

  epoch_start: 0
  epoch_end: 5
  epoch_step: 1

  perform_post: False

decoder:
  # Pretrained uncertainty model to use
  pretrained_path_unc: '/mnt/hdd/thesis/results/cifar10_resnet34_maha/state_dicts/cifar10_resnet34_maha_uncertain_post.pth'

  # Decoder setup
  forward_type: 'layers'
  use_layers: [0,null]  
  num_filt: 128
  pretrained_path: 
  
  # Training parameters
  epochs: 1
  start_epoch: 0
  batch_size: 64

  criterion: 'bce'

  optimizer: 'adam'
  lr: 0.0005
  betas: [0.9, 0.999]
  weight_decay: 0

  scheduler: step_lr
  step_size: 20
  gamma: 0.1

  save_every: 1

decoder_inference:
  pretrained_path_unc: '/mnt/hdd/thesis/results/cifar10_resnet34_maha/state_dicts/cifar10_resnet34_maha_uncertain_post.pth'
  pretrained_path_decoder: '/mnt/hdd/thesis/results/cifar10_resnet34_basic/state_dicts_decoder/cifar10_resnet34_basic_decoder_0.pth'

  image_sim_measure: ['LPIPS', 'GMSD']
  dataset_ood_test: ['svhn', 'tiny_imagenet']


decoder_evaluation:
  pretrained_path_unc: '/mnt/hdd/thesis/results/cifar10_resnet34_basic/state_dicts/cifar10_resnet34_basic_uncertain_post.pth'
  pretrained_path_decoder: '/mnt/hdd/thesis/results/cifar10_resnet34_basic/state_dicts_decoder/cifar10_resnet34_basic_decoder_0.pth'
  inference_dir: '/mnt/hdd/thesis/results/cifar10_resnet34_basic/inference_decoder/'

  image_sim_measure: ['LPIPS', 'GMSD']
  dataset_ood_test: ['svhn', 'tiny_imagenet'] 


imagenet_c:
  pretrained_path_unc: '/mnt/hdd/thesis/results/cifar10_resnet34_basic/state_dicts/cifar10_resnet34_basic_uncertain_post.pth'
  datasets: ['blur+defocus_blur', 'digital+contrast']

  


